spring:
  thymeleaf:
    cache: false
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: classpath:templates/
      suffix: .html
  resources:
    cache:
      cachecontrol:
        max-age: 3600
  datasource:
    url: jdbc:h2:tcp://localhost/~/test;
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        query:
          in_clause_parameter_padding: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace