server:
  port: 80
  context-path: /
  display-name: server
  tomcat:
    uri-encoding: UTF-8
    
spring:
  thymeleaf:
    cache: false
  mvc:
    servlet:
      load-on-startup: 1
    view:
      prefix: classpath:templates/
      suffix: .html
    static-path-pattern: /static/*
  resources:
    add-mappings: true
    cache-period: 3600
    static-locations:
    - classpath:static/
  datasource:
    dbcp2:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useSSL=false
      username: test
      password: test
      initial-size: 10
      min-idle: 10
      max-idle: 20
      max-total: 20
      max-wait-millis: 3000
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 3600000
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      validation-query: SELECT 1
  session:
    store-type: none

mybatis:
  config-location: classpath:mybatis-config-base.xml
  mapper-locations: classpath:mappers/*-mapper.xml
